version: "3.8"

services:
  order-service:
    container_name: order-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5002:5002
