version: "3.8"

services:
  product-service:
    container_name: product-service
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - 5001:5001
